[fud2] Improve Error Message When Ninja Is Not Installed (#2255)
The error message has been changed from
```
No such file or directory (os error 2)
```
to
```
Error: Unable to run ninja "No such file or directory (os error 2)"
Hint: Is ninja installed correctly?
```

This is intended to close #2254